version: '3.1'

services:
    db:
        image: postgres:12
        environment:
            - POSTGRES_PASSWORD_FILE=/secrets/postgres_password.txt
        volumes:
            - ./database:/var/lib/postgresql/data
            - ./secrets:/secrets
        restart: always

    bolt:
        image: chibicitiberiu/bolt-cms
        environment:
            - DB_HOST=db
            - DB_NAME=bolt
            - DB_PORT=3306
            - DB_USERNAME=bolt
            - DB_PASSWORD=boltpass123
        volumes:
            - config_dir:/var/www/html/app/config
            - database_dir:/var/www/html/app/database
            - files_dir:/var/www/html/public/files
            - extensions_dir:/var/www/html/extensions
        depends-on:
            - db